### ISSUE TITLE
HTTPS Security warning in the website

### ISSUE THREAD

**Issue by BurakUeda** [jamescroft/fontawesome-cheatsheet#3]
https://fontawesome.bootstrapcheatsheets.com/
Google Chrome giving me security warnings:

> Active Mixed Content
> You have recently allowed non-secure content (such as scripts or iframes) to run on this site.

Non-secure origins:

- http://fonts.googleapis.com
- http://netdna.bootstrapcdn.com
- http://fonts.gstatic.com
- http://code.jquery.com

**Comment by jamescroft** [comment]
Thanks for the pickup! I've recently switched over to HTTPS, and changed the non-secure sources to one sheet, but not the other! I've updated it now, hopefully that's fixed the issue.
